name       : mps-youtube
version    : 0.2.8
release    : 4
source     :
    - git|https://github.com/mps-youtube/mps-youtube : 7b95b9c8cfab164958e9320c686fc0608126e9c7
homepage   : https://github.com/mps-youtube/mps-youtube
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Terminal based YouTube jukebox with playlist management
description: |
    Terminal based YouTube jukebox with playlist management
builddeps  :
    - pkgconfig(python3)
    - python-pafy
rundeps    :
    - mpv
    - python-pafy
    - python-pyperclip
build      : |
    %python3_setup
install    : |
    %python3_install

