name       : mps-youtube
version    : 0.2.8
release    : 1
source     :
    - https://github.com/mps-youtube/mps-youtube/archive/v0.2.8.tar.gz : d5f2c4bc1f57f0566242c4a0a721a5ceaa6d6d407f9d6dd29009a714a0abec74
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Terminal based YouTube jukebox with playlist management
description: |
    Terminal based YouTube jukebox with playlist management
builddeps  :
    - pkgconfig(python3)
    - python-pafy
rundeps    :
    - mpv
    - python-pafy
build      : |
    %python3_setup
install    : |
    %python3_install

